

### GET ALL CONTACTS
GET http://localhost:3000/users

### GET ONLY ONE 
GET http://localhost:3000/users/67369941ca2d411bf1c69aab

### CREATE NEW CONTACT 
POST http://localhost:3000/users/
content-type: application/json

{
    "firstName": "Joaquin",
    "lastName": "Tapia",
    "email": "joaco@yahoo.com",
    "favoriteColor": "black",
    "birthday": "1999-05-14"
}


### UPDATE CONTACT
PUT http://localhost:3000/users/6738249d96ef007d716e2717
content-type: application/json

{
   "firstName": "Joaquin3",
    "lastName": "Tapia3",
    "email": "joaco3@yahoo.com",
    "favoriteColor": "black",
    "birthday": "1999-05-14"
}



### DELETE CONTACT 
DELETE http://localhost:3000/users/6738249d96ef007d716e2717








### GET ALL CONTACTS ON RENDER
GET https://project1-et34.onrender.com/users


### GET ONLY ONE ON RENDER
GET https://project1-et34.onrender.com/users/673698ffca2d411bf1c69aa9



### CREATE NEW CONTACT ON RENDER
POST https://project1-et34.onrender.com/users/
content-type: application/json

{
    "firstName": "Joaquin",
    "lastName": "Tapia",
    "email": "joaco@yahoo.com",
    "favoriteColor": "black",
    "birthday": "1999-05-14"
}


### UPDATE CONTACT ON RENDER
PUT https://project1-et34.onrender.com/users/673940265c30bd12c1fe7300
content-type: application/json

{
   "firstName": "Joaquin3",
    "lastName": "Tapia3",
    "email": "joaco3@yahoo.com",
    "favoriteColor": "black",
    "birthday": "1999-05-14"
}
